
[[audits.anstyle-query]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.1.3 -> 1.1.5"
aggregated-from = "https://raw.githubusercontent.com/loot/metadata-validator/refs/heads/master/supply-chain/audits.toml"

[[audits.anstyle-wincon]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "3.0.9 -> 3.0.11"
aggregated-from = "https://raw.githubusercontent.com/loot/metadata-validator/refs/heads/master/supply-chain/audits.toml"

[[audits.clap]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "4.5.40 -> 4.5.47"
aggregated-from = "https://raw.githubusercontent.com/loot/metadata-validator/refs/heads/master/supply-chain/audits.toml"

[[audits.clap_builder]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "4.5.40 -> 4.5.47"
aggregated-from = "https://raw.githubusercontent.com/loot/metadata-validator/refs/heads/master/supply-chain/audits.toml"

[[audits.codespan-reporting]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.12.0 -> 0.13.1"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.convert_case]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.8.0 -> 0.10.0"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.ctor]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.4.2 -> 0.6.3"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.ctor-proc-macro]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.0.5 -> 0.0.7"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.cxx]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.0.161 -> 1.0.192"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.cxx-build]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.0.161 -> 1.0.192"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.cxxbridge-flags]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.0.161 -> 1.0.192"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.cxxbridge-macro]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.0.161 -> 1.0.192"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.dtor]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.0.6 -> 0.1.1"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.dtor-proc-macro]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.0.5 -> 0.0.6"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.errno]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.3.12 -> 0.3.14"
aggregated-from = "https://raw.githubusercontent.com/loot/metadata-validator/refs/heads/master/supply-chain/audits.toml"

[[audits.libloading]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.8.6 -> 0.8.9"
notes = "Mostly formatting changes, plus swaps windows-targets for windows-link, and adds a new function that looks fine."
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.libloading]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.8.9 -> 0.9.0"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.link-cplusplus]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.0.10 -> 1.0.12"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.log]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.4.28 -> 0.4.29"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.napi]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-run"
delta = "3.1.6 -> 3.8.1"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.napi]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "3.8.1 -> 3.8.2"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.napi-build]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "2.2.3 -> 2.3.1"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.napi-derive]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "3.2.2 -> 3.5.0"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.napi-derive]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "3.5.0 -> 3.5.1"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.napi-derive-backend]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "2.1.2 -> 5.0.0"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.napi-derive-backend]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "5.0.0 -> 5.0.1"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.napi-sys]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "3.0.0 -> 3.2.1"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.proc-macro2]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.0.105 -> 1.0.106"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.regex]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.11.2 -> 1.11.3"
notes = "It just increments the minimum version of regex-automata."
aggregated-from = "https://raw.githubusercontent.com/loot/loot-condition-interpreter/refs/heads/master/supply-chain/audits.toml"

[[audits.regex]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.11.3 -> 1.12.2"
aggregated-from = "https://raw.githubusercontent.com/loot/loot-condition-interpreter/refs/heads/master/supply-chain/audits.toml"

[[audits.regex-automata]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.4.9 -> 0.4.11"
notes = "It's a combination of format!() syntax tweaks and added calls to .shrink_to_fit()."
aggregated-from = "https://raw.githubusercontent.com/loot/loot-condition-interpreter/refs/heads/master/supply-chain/audits.toml"

[[audits.regex-automata]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.4.11 -> 0.4.13"
aggregated-from = "https://raw.githubusercontent.com/loot/loot-condition-interpreter/refs/heads/master/supply-chain/audits.toml"

[[audits.regress]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.10.4 -> 0.10.5"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[audits.slab]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.4.8 -> 0.4.11"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[trusted.esplugin]]
criteria = "safe-to-deploy"
trusted-publisher = "github:Ortham/esplugin"
start = "2025-09-29"
end = "2027-01-19"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[trusted.esplugin]]
criteria = "safe-to-deploy"
trusted-publisher = "github:Ortham/esplugin"
start = "2025-09-29"
end = "2027-01-19"
notes = "This is my own crate, published from my own Git repo using Trusted Publishing."
aggregated-from = "https://raw.githubusercontent.com/loot/loot-condition-interpreter/refs/heads/master/supply-chain/audits.toml"

[[trusted.esplugin]]
criteria = "safe-to-deploy"
trusted-publisher = "github:Ortham/esplugin"
start = "2025-09-29"
end = "2027-01-26"
aggregated-from = "https://raw.githubusercontent.com/loot/metadata-validator/refs/heads/master/supply-chain/audits.toml"

[[trusted.futures-task]]
criteria = "safe-to-deploy"
user-id = 33035
start = "2019-07-29"
end = "2027-01-06"
notes = "taiki-e is a member of the rust-lang GitHub org and of the Rust language's async working group, and the source repo is owned by the rust-lang GitHub org."
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[trusted.futures-util]]
criteria = "safe-to-deploy"
user-id = 33035
start = "2020-10-05"
end = "2027-01-06"
notes = "taiki-e is a member of the rust-lang GitHub org and of the Rust language's async working group, and the source repo is owned by the rust-lang GitHub org."
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 55123
start = "2024-08-15"
end = "2026-09-16"
notes = "rust-lang-owner is a bot run by the Rust Infrastructure Team, so libc is hopefully as trustworthy as the Rust toolchain."
aggregated-from = "https://raw.githubusercontent.com/loot/loot-condition-interpreter/refs/heads/master/supply-chain/audits.toml"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 55123
start = "2024-08-15"
end = "2026-09-28"
aggregated-from = "https://raw.githubusercontent.com/loot/metadata-validator/refs/heads/master/supply-chain/audits.toml"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 55123
start = "2024-08-15"
end = "2026-09-28"
notes = "rust-lang-owner is a bot managed by the Rust language's infrastructure team, and the source repo is owned by the rust-lang GitHub org."
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[trusted.libloadorder]]
criteria = "safe-to-deploy"
trusted-publisher = "github:Ortham/libloadorder"
start = "2025-08-01"
end = "2027-01-19"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[trusted.libloadorder]]
criteria = "safe-to-deploy"
trusted-publisher = "github:Ortham/libloadorder"
start = "2025-08-01"
end = "2027-01-26"
aggregated-from = "https://raw.githubusercontent.com/loot/metadata-validator/refs/heads/master/supply-chain/audits.toml"

[[trusted.libloot]]
criteria = "safe-to-deploy"
trusted-publisher = "github:loot/libloot"
start = "2025-08-11"
end = "2027-01-26"
aggregated-from = "https://raw.githubusercontent.com/loot/metadata-validator/refs/heads/master/supply-chain/audits.toml"

[[trusted.loot-condition-interpreter]]
criteria = "safe-to-deploy"
trusted-publisher = "github:loot/loot-condition-interpreter"
start = "2025-09-29"
end = "2027-01-19"
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[trusted.loot-condition-interpreter]]
criteria = "safe-to-deploy"
trusted-publisher = "github:loot/loot-condition-interpreter"
start = "2025-09-29"
end = "2027-01-26"
aggregated-from = "https://raw.githubusercontent.com/loot/metadata-validator/refs/heads/master/supply-chain/audits.toml"

[[trusted.windows-link]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2022-09-01"
end = "2026-09-17"
notes = "kennykerr is on the Windows team at Microsoft."
aggregated-from = "https://raw.githubusercontent.com/loot/loot-condition-interpreter/refs/heads/master/supply-chain/audits.toml"

[[trusted.windows-link]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2024-07-17"
end = "2026-09-28"
notes = "kennykerr is on the Windows team at Microsoft."
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[trusted.windows-link]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2024-07-17"
end = "2026-09-28"
notes = "kennykerr is on the Windows team at Microsoft."
aggregated-from = "https://raw.githubusercontent.com/loot/metadata-validator/refs/heads/master/supply-chain/audits.toml"

[[trusted.windows-result]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2024-02-02"
end = "2026-09-28"
notes = "kennykerr is on the Windows team at Microsoft."
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[trusted.windows-result]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2024-02-02"
end = "2026-09-28"
notes = "kennykerr is on the Windows team at Microsoft."
aggregated-from = "https://raw.githubusercontent.com/loot/metadata-validator/refs/heads/master/supply-chain/audits.toml"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-11-15"
end = "2026-09-17"
notes = "kennykerr is on the Windows team at Microsoft."
aggregated-from = "https://raw.githubusercontent.com/loot/loot-condition-interpreter/refs/heads/master/supply-chain/audits.toml"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-11-15"
end = "2026-09-28"
notes = "kennykerr is on the Windows team at Microsoft."
aggregated-from = "https://raw.githubusercontent.com/loot/libloot/refs/heads/master/supply-chain/audits.toml"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2021-11-15"
end = "2026-09-28"
notes = "kennykerr is on the Windows team at Microsoft."
aggregated-from = "https://raw.githubusercontent.com/loot/metadata-validator/refs/heads/master/supply-chain/audits.toml"

[[trusted.windows-targets]]
criteria = "safe-to-deploy"
user-id = 64539
start = "2022-09-09"
end = "2026-09-17"
notes = "kennykerr is on the Windows team at Microsoft."
aggregated-from = "https://raw.githubusercontent.com/loot/loot-condition-interpreter/refs/heads/master/supply-chain/audits.toml"
